### ISSUE TITLE
Decide whether to use CommonJS/Browserify for JS build process

### ISSUE THREAD

**Issue by TGOlson** [grokkerlab/grokker#25]
CommonJS (`require` statements) takes a little more than originally thought to make it play well with Angular. Here is a good post describing the process: https://blog.codecentric.de/en/2014/08/angularjs-browserify/

We should decide if we still want to take that approach, or use the more traditional approach of concatenating all the vendor scripts and source scripts with gulp.

**Comment by jackfirth** [comment]
I really like how you can write the functions entirely separate from Angular in that style, that would be very useful.

**Comment by TGOlson** [comment]
Ditto - as I was reading through the blog post and all the hoops you have to jump through I started to doubt the practicality of using CommonJS. But at the end when they showed the independent modules, and how easy testing is, I was pretty hooked. I'm game to try it out - should be a good experiment.

**Comment by jackfirth** [comment]
Once #21 is merged in, it should be easy to experiment with that on a branch
