### ISSUE TITLE
Javascript code should be linted

### ISSUE THREAD

**Issue by jackfirth** [grokkerlab/grokker#27]
Jslint is pretty standard, but eslint is more configurable. SweetJS and ES6 should be taken into consideration.

**Comment by TGOlson** [comment]
Yes! Great issue to bring up. I've been interested in eslint for a while. I'm not sure if we will need the extra configuration, but at the very least it does what jslint does just as well. Plus, I think I saw an update where the atom linter-eslint now supports preprocessing, so in theory we could use sweetjs and have it link without failing too..

**Comment by jackfirth** [comment]
Definitely seems like eslint is the way to go then, at the very least for allowing future flexibility
